:development:
  :captcha_key: 6Y7E402rgYu2FdM5m0yVMgnZ2CSSeEwNNMl5sbXl
  :captcha_username: mattpayne
  :connection_string: mysql://root:2324@localhost/mattpayne_dev
  :tumblr_url: http://mpayne.tumblr.com/api/read?type=regular&num=5
  :github_url: http://github.com/api/v1/xml/mattapayne
  :admin_username: mattpayne
  :admin_password: monkeybutler
  :vendor:
    /sinatra/lib: sinatra

:test:
  :captcha_key: 6Y7E402rgYu2FdM5m0yVMgnZ2CSSeEwNNMl5sbXl
  :captcha_username: mattpayne
  :connection_string: mysql://root:2324@localhost/mattpayne_dev
  :tumblr_url: http://mpayne.tumblr.com/api/read?type=regular&num=5
  :github_url: http://github.com/api/v1/xml/mattapayne
  :admin_username: mattpayne
  :admin_password: monkeybutler
  :vendor:
    /sinatra/lib: sinatra

:production:
  :captcha_key: 6Y7E402rgYu2FdM5m0yVMgnZ2CSSeEwNNMl5sbXl
  :captcha_username: mattpayne
  :connection_string: mysql://root:2324@localhost/mattpayne_dev
  :tumblr_url: http://mpayne.tumblr.com/api/read?type=regular&num=5
  :github_url: http://github.com/api/v1/xml/mattapayne
  :admin_username: mattpayne
  :admin_password: monkeybutler
  :vendor:
    /sinatra/lib: sinatra
